name: grid_frontend
description: "Grid: Private Location Sharing"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_map: ^7.0.2
  timeago: ^3.1.0
  latlong2: ^0.9.1
  flutter_map_marker_popup: ^7.0.0
  flutter_map_location_marker: ^9.1.1
  flutter_map_marker_cluster: ^1.3.6
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  matrix: ^0.29.8
  flutter_olm: ^2.0.0
  flutter_openssl_crypto: ^0.5.0
  flutter_secure_storage: ^9.2.2
  flutter_emoji: ^2.5.1
  path_provider: ^2.1.4
  sqflite: ^2.3.3+1
  crypto: ^3.0.4
  encrypt: ^5.0.3
  flutter_map_cancellable_tile_provider: ^3.0.2  # Downgraded to a compatible version
  flutter_launcher_icons: ^0.14.2
  random_avatar: any # or the latest version on Pub
  url_launcher: ^6.3.0
  http: ^1.2.2
  vector_map_tiles: ^8.0.0
  vector_map_tiles_pmtiles: ^1.3.0
  intl_phone_field: ^3.2.0
  lottie: ^3.1.2
  sleek_circular_slider: ^2.0.1
  flutter_slidable: ^3.1.1
  flutter_dotenv: ^5.1.0
  permission_handler: ^11.3.1
  qr_flutter: ^4.1.0
  flutter_bloc: ^8.1.6
  collection: ^1.18.0
  equatable: ^2.0.7
  flutter_background_geolocation: ^4.16.5
  hive: ^2.2.3
  qr_code_scanner_plus: ^2.0.6
  package_info_plus: ^8.1.2


flutter_launcher_icons:
  android: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/appIcons/playstore.png"
  adaptive_icon_padding: false #
  ios: true
  image_path: "assets/appIcons/appstore.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/Jpeg-2.jpg
    - assets/logos/png-file-2.png
    - assets/logos/Brand-Pattern-Full-Color.png
    - assets/logos/Brand-Pattern-Low-color.png
    - assets/lottie/lottie-phone-pin.json
    - assets/lottie/lottie-phone-verify.json
    - .env

  fonts:
    - family: GridFont
      fonts:
        - asset: assets/fonts/fontawesome-webfont.ttf
          weight: 700
